/* Bilingual UI regressions. Tooling: see tests/test_journey.js. */
const {chromium}=require('@playwright/test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),{createServer}=require('node:http');
const root=path.resolve(__dirname,'../web');const server=createServer(async(q,s)=>{try{const f=path.resolve(root,'.'+(q.url==='/'?'/index.html':q.url));if(!f.startsWith(root+path.sep))throw Error('path');s.setHeader('Content-Type',f.endsWith('.js')?'text/javascript':f.endsWith('.json')?'application/json':'text/html');s.end(await fs.readFile(f));}catch{s.statusCode=404;s.end();}});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const url='http://127.0.0.1:'+server.address().port,b=await chromium.launch();let checks=0;
try{for(const width of [390,1280]){
 const c=await b.newContext({viewport:{width,height:850}}),p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(url);await p.waitForSelector('#kpis .card');assert.equal(await p.locator('html').getAttribute('lang'),'pt-BR');checks++;
 await p.click('#tab-value');await p.fill('#price-0','171.25');await p.click('#valuation-apply');const before=await p.locator('#price-0').inputValue();await p.selectOption('#language','en');assert.equal(await p.locator('#price-0').inputValue(),before);assert.equal(await p.locator('#tab-value').getAttribute('aria-selected'),'true');checks++;
 for(const [id,title] of [['overview','Cost allocation'],['holdings','Invented holdings'],['ledger','Invented history'],['income','Invented income'],['value','Invented value and exposure'],['goals','Invented goals and scenarios'],['multi','Invented multi-currency account']]){
  await p.click('#tab-'+id);assert((await p.locator('#'+id).innerText()).includes(title));assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.screenshot({path:'/downloads/inv-language-'+width+'-'+id+'.png'});checks++;
 }
 assert((await p.locator('#kpis').innerText()).includes('4,627.00'));assert((await p.locator('#income-totals').innerText()).includes('Received net: SEK'));checks++;
 await p.fill('#multi-rate','0');await p.click('#multi-apply');assert((await p.locator('#multi-status').innerText()).startsWith('Invalid input.'));await p.selectOption('#language','pt-BR');assert((await p.locator('#multi-status').innerText()).startsWith('Entrada inválida.'));await p.selectOption('#language','en');checks++;
 await p.click('#tab-income');await p.selectOption('#income-state','received');await p.selectOption('#language','pt-BR');assert.equal(await p.locator('#income-state').inputValue(),'received');await p.selectOption('#language','en');assert.equal(await p.locator('#income-state').inputValue(),'received');checks++;
 await p.click('#tab-holdings');await p.fill('#search','absent');assert((await p.locator('#positions').innerText()).startsWith('No invented company'));await p.selectOption('#language','pt-BR');assert.equal(await p.locator('#search').inputValue(),'absent');assert((await p.locator('#positions').innerText()).startsWith('Nenhuma empresa'));checks++;
 await p.selectOption('#language','en');await p.reload();await p.waitForSelector('#kpis .card');assert.equal(await p.locator('html').getAttribute('lang'),'en');assert.equal(await p.evaluate(()=>localStorage.getItem('investor-os-language')),'en');checks++;
 const download=p.waitForEvent('download');await p.click('#export');const d=await download,stream=await d.createReadStream(),chunks=[];for await(const x of stream)chunks.push(x);assert.deepEqual(JSON.parse(Buffer.concat(chunks).toString()),JSON.parse(await fs.readFile(path.join(root,'portfolio.json'),'utf8')));checks++;
 await p.click('#reset');assert((await p.locator('#status').innerText()).startsWith('Initial view restored'));assert.equal(await p.locator('#language').inputValue(),'en');checks++;
 await p.route('**/portfolio.json',r=>r.abort());await p.reload();await p.getByText('Could not load the demo.',{exact:false}).waitFor();await p.selectOption('#language','pt-BR');assert((await p.locator('#status').innerText()).startsWith('Não foi possível'));assert.deepEqual(errors,[]);checks++;
 await c.close();
}
const c=await b.newContext();await c.addInitScript(()=>{Storage.prototype.getItem=()=>{throw Error('blocked')};Storage.prototype.setItem=()=>{throw Error('blocked')};});const p=await c.newPage();await p.goto(url);await p.waitForSelector('#kpis .card');await p.selectOption('#language','en');assert.equal(await p.locator('html').getAttribute('lang'),'en');checks++;await c.close();
}finally{await b.close();server.close();}console.log(checks+' language checks passed');})().catch(e=>{console.error(e);server.close();process.exitCode=1});
