(function(root){
'use strict';const T=InvestorI18n.t;let codes,history,selected='VND';const el=id=>document.getElementById(id),defaults={SEK:'0.0004',USD:'0.00004'},historic={SEK:'0.0005',USD:'0.00005'};let rates;
function fresh(){history={currency:'VND',local_cost:'200000',date:'2026-01-01',fx:{}};rates={SEK:defaults.SEK,USD:defaults.USD};for(const to of ['SEK','USD'])history.fx[to]={from:'VND',to,rate:historic[to],date:history.date,source:T('Histórico inteiramente fictício')};}
function format(v,c){if(v===null)return T('Indisponível');const x=codes.find(x=>x.code===c);const opts={style:'currency',currency:c};if(x?.minor_units!==null&&x?.minor_units!==undefined)opts.minimumFractionDigits=opts.maximumFractionDigits=x.minor_units;return new Intl.NumberFormat(InvestorI18n.locale==='en'?'en-US':'pt-BR',opts).format(Number(v));}
function pair(){const base=el('multi-base').value,c=el('multi-local').value;el('multi-pair').textContent='1 '+c+' = X '+base+T(' (FX do snapshot)');el('multi-rate').value=c===base?'1':rates[base]||'';el('multi-rate').readOnly=c===base;el('multi-history-label').textContent=T('Câmbio da operação: 1 ')+c+' = X '+base;el('multi-historical-rate').value=c===base?'1':history.fx[base]?.rate||'';el('multi-historical-rate').readOnly=c===base;}
function apply(){const out=el('multi-results');out.replaceChildren();try{
 const base=el('multi-base').value,c=el('multi-local').value;if(c!==selected)throw Error('Choose currency first');rates[base]=el('multi-rate').value;
 if(c!==base)history.fx[base]={from:c,to:base,rate:el('multi-historical-rate').value,date:history.date,source:T('Histórico inteiramente fictício')};
 const row={id:'fictional-delta',currency:c,quantity:el('multi-quantity').value,price:el('multi-price').value,price_date:el('multi-price-date').value,source:el('multi-source').value,market_fx:{from:c,to:base,rate:el('multi-rate').value,date:el('multi-fx-date').value,source:el('multi-source').value},history};
 const r=InvestorMulti.snapshot([row],base,el('multi-asof').value,codes.map(x=>x.code));el('multi-status').textContent=r.complete?T('Snapshot fictício completo. Sem feed ou dados reais.'):T('FX faltante: total indisponível. Subtotal conhecido não é total.');
 const a=r.rows[0];for(const text of ['Fictional Delta Lantern: '+format(a.local_value,c)+T(' local = ')+format(a.market_base,base)+T(' na base ')+base,T('Custo original preservado: ')+format(a.original_cost,a.cost_currency)+T(' em ')+history.date+T('; custo histórico na base: ')+format(a.cost_base,base),T('Resultado não realizado: ')+format(a.unrealized,base)+T('. Mercado usa FX atual do snapshot; custo usa FX da operação.'),T('Total (')+base+'): '+format(r.total,base)+T(' · conhecido: ')+format(r.known_total,base)]){const p=document.createElement('p');p.textContent=text;out.append(p)}
 }catch(e){el('multi-status').textContent=T('Entrada inválida. Escolha um código da lista; datas de preço/FX devem coincidir e não exceder a avaliação; FX positivo. Nenhum valor estimado.');}}
function render(list){codes=list.codes;const dl=el('multi-codes');list.codes.forEach(c=>{const o=document.createElement('option');o.value=c.code;o.label=c.name;dl.append(o)});fresh();
 el('multi-base').onchange=()=>{pair();apply()};el('multi-local').onchange=()=>{const c=el('multi-local').value;if(!codes.some(x=>x.code===c)){apply();return}selected=c;history={currency:c,local_cost:'200000',date:'2026-01-01',fx:{}};rates={};pair();apply();el('multi-status').textContent+=T(' Moeda local trocada: este é um NOVO exemplo fictício, histórico de conversão limpo.')};el('multi-apply').onclick=apply;pair();apply();}
function reset(){selected='VND';el('multi-local').value='VND';el('multi-base').value='SEK';el('multi-quantity').value='10';el('multi-price').value='25000';el('multi-price-date').value=el('multi-fx-date').value=el('multi-asof').value='2026-01-31';el('multi-source').value=T('Exemplo inteiramente fictício');fresh();pair();apply();}
root.InvestorMultiView={render,reset,refresh:()=>{const base=el('multi-base').value,c=el('multi-local').value;el('multi-pair').textContent='1 '+c+' = X '+base+T(' (FX do snapshot)');el('multi-history-label').textContent=T('Câmbio da operação: 1 ')+c+' = X '+base;apply();}};
})(globalThis);
