(function(root){
'use strict';const el=id=>document.getElementById(id),money=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'SEK'}).format(Number(v));
const fields=[['initial','Capital inicial fictício (SEK)','10000'],['annual','Aporte ao fim de cada ano (SEK)','1200'],['yield','Yield bruto assumido (fração, 0.04 = 4%)','0.04'],['withholding','Retenção assumida (fração)','0.15'],['inflation','Inflação assumida (fração)','0.02'],['target','Meta líquida mensal fictícia (SEK)','100'],['contributionGoal','Meta de aporte anual (SEK)','1200'],['contributed','Aporte externo feito no ano (SEK)','600'],['years','Horizonte (1-50 anos)','10'],['low','Retorno total conservador (fração)','-0.02'],['base','Retorno total base (fração)','0.04'],['high','Retorno total otimista (fração)','0.06']];
function apply(){const out=el('goal-results');out.replaceChildren();try{const x=Object.fromEntries(fields.map(([k])=>[k,el('goal-'+k).value]));x.years=Number(x.years);const r=InvestorScenarios.project(x);el('goal-status').textContent='Cenários ilustrativos. Sem garantia de renda ou prazo.';const p=document.createElement('p');p.textContent='Aporte anual: '+r.annual_progress.toFixed(2)+'% (barra limitada a '+r.annual_display.toFixed(2)+'%). Renda mensal inicial estimada: '+money(r.current_monthly_income)+' · '+r.income_progress.toFixed(2)+'% da meta.';out.append(p);[['Aporte anual',r.annual_display],['Renda mensal',r.income_display]].forEach(([label,value])=>{const b=document.createElement('div');b.className='bar';b.setAttribute('role','progressbar');b.setAttribute('aria-label',label);b.setAttribute('aria-valuenow',value);b.setAttribute('aria-valuemin','0');b.setAttribute('aria-valuemax','100');const fill=document.createElement('span');fill.style.width=value+'%';b.append(fill);out.append(b)});
 r.scenarios.forEach(s=>{const block=document.createElement('div');block.className='asset';const h=document.createElement('h3');h.textContent=s.name;const note=document.createElement('p');note.textContent=s.estimated_target_year?'Meta nominal de renda atingida no ano '+s.estimated_target_year+' APENAS sob estas hipóteses.':'Meta de renda não atingida no horizonte sob estas hipóteses.';block.append(h,note);s.rows.forEach(row=>{const p=document.createElement('p');p.textContent='Ano '+row.year+': capital nominal '+money(row.capital)+' · capital em poder de compra inicial '+money(row.capital_today)+' · renda mensal nominal estimada '+money(row.monthly_income);block.append(p)});out.append(block)});
 }catch(e){el('goal-status').textContent='Entrada inválida. Use decimais não negativos com ponto; metas positivas; retorno entre -1 e 1 (ordenado conservador ≤ base ≤ otimista), outras taxas entre 0 e 1; horizonte inteiro de 1 a 50. Nenhum cenário foi estimado.';}}
function render(){const dest=el('goal-inputs');dest.replaceChildren();fields.forEach(([k,label,v])=>{const l=document.createElement('label');l.htmlFor='goal-'+k;l.textContent=label;const n=document.createElement('input');n.id='goal-'+k;n.value=v;n.type='text';n.autocomplete='off';dest.append(l,n)});el('goal-apply').onclick=apply;apply();}
function reset(){fields.forEach(([k,l,v])=>el('goal-'+k).value=v);apply();}
root.InvestorGoals={render,reset};
})(globalThis);
